version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev # Use Dockerfile if you're not in development mode
    container_name: tmdb-app
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/tmdb-app
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=omar
      - ME_CONFIG_BASICAUTH_PASSWORD=12345678
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
