version: '3.8'

services:
  app:
    build: .
    container_name: tmdb-app
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/tmdb-app
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
